geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/',  adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.ProductCategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),
    path('products/create/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/', adminapp.ProductListView.as_view(), name='products'),
    path('products/read/category/<int:category_pk>/', adminapp.ProductListView.as_view(), name='products_by_category'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/',  include('mainapp.urls', namespace='products')),
    path('product_detail/<int:pk>/', mainapp.product_detail, name='product_detail'),
    path('contact/', mainapp.contacts, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django.contrib.auth.forms import UserChangeForm
from authapp.models import ShopUser
from authapp.forms import ShopUserRegisterForm
from django import forms
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ShopUserAdminRegisterForm(ShopUserRegisterForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductCategoryAdminForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.views.generic.list import ListView
from .forms import ShopUserAdminEditForm, ShopUserAdminRegisterForm, ProductCategoryAdminForm, ProductAdminForm


class IsSuperUserView(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


class UsersListView(IsSuperUserView, ListView):
    model = ShopUser
    template_name = 'adminapp/list.html'
    queryset = ShopUser.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UsersListView, self).get_context_data(**kwargs)
        context['title'] = 'Пользователи'
        context['create_tag'] = 'Добавить нового пользователя'
        context['create_link'] = 'admin_custom:user_create'
        context['update_link'] = 'admin_custom:user_update'
        context['users'] = ShopUser.objects.all()
        return context


class UserUpdateView(IsSuperUserView, UpdateView):
    model = ShopUser
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('admin_custom:users')
    form_class = ShopUserAdminEditForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        title = ShopUser.objects.get(pk=self.kwargs.get('pk')).username
        context['title'] = 'Изменение пользователя: {}'.format(title)
        context['tag'] = 'Удалить пользователя'
        context['delete_link'] = 'admin_custom:user_delete'
        return context


class UserCreateView(IsSuperUserView, CreateView):
    model = ShopUser
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('admin_custom:users')
    form_class = ShopUserAdminRegisterForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание нового пользователя. Админка'
        context['tag'] = 'Удалить категорию'
        return context


class UserDeleteView(IsSuperUserView, DeleteView):
    model = ShopUser
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('admin_custom:users')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserDeleteView, self).get_context_data(**kwargs)
        title = ShopUser.objects.get(pk=self.kwargs.get('pk')).username
        context['title'] = 'Удаление {}. Админка'.format(title)
        return context


class ProductCategoriesListView(IsSuperUserView, ListView):
    model = ProductCategory
    template_name = 'adminapp/list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoriesListView, self).get_context_data(**kwargs)
        context['title'] = 'Категории'
        context['create_tag'] = 'Создать новую категорию'
        context['create_link'] = 'admin_custom:category_create'
        context['update_link'] = 'admin_custom:category_update'
        context['categories'] = ProductCategory.objects.all()
        return context


class ProductCategoryUpdateView(IsSuperUserView, UpdateView):
    model = ProductCategory
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('admin_custom:categories')
    form_class = ProductCategoryAdminForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data(**kwargs)
        title = ProductCategory.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Изменение категории: {}'.format(title)
        context['tag'] = 'Удалить категорию'
        context['delete_link'] = 'admin_custom:category_delete'
        return context


class ProductCategoryDeleteView(IsSuperUserView, DeleteView):
    model = ProductCategory
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('admin_custom:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryDeleteView, self).get_context_data(**kwargs)
        title = ProductCategory.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Удаление {}'.format(title)
        return context


class ProductCategoryCreateView(IsSuperUserView, CreateView):
    model = ProductCategory
    template_name = 'adminapp/object_update.html'
    success_url = reverse_lazy('admin_custom:categories')
    form_class = ProductCategoryAdminForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание новой категории.'
        context['tag'] = 'Удалить категорию'
        return context


class ProductListView(IsSuperUserView, ListView):
    model = Product
    template_name = 'adminapp/products.html'
    queryset = Product.objects.all()

    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset()
        if self.kwargs.get('category_pk'):
            queryset = queryset.filter(category=self.kwargs.get('category_pk'))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['title'] = 'Все продукты. Админка'
        context['categories'] = ProductCategory.objects.all()
        return context


class ProductDetailView(IsSuperUserView, DetailView):
    model = Product
    template_name = 'adminapp/product.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = '{}. Админка'.format(title)
        return context


class ProductCreateView(IsSuperUserView, CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin_custom:products')
    fields = '__all__'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание нового продукта. Админка'
        return context


class ProductDeleteView(IsSuperUserView, DeleteView):
    model = Product
    template_name = 'adminapp/object_delete.html'
    success_url = reverse_lazy('admin_custom:products')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDeleteView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Удаление {}. Админка'.format(title)
        return context


class ProductUpdateView(IsSuperUserView, UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('admin_custom:products')
    form_class = ProductAdminForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        title = Product.objects.get(pk=self.kwargs.get('pk')).name
        context['title'] = 'Изменение {}. Админка'.format(title)
        return context

    def get_success_url(self):
        return reverse_lazy('admin_custom:product_read', kwargs={'pk': self.kwargs.get('pk')})

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Админка</title>
    {% endblock %}

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
    <h2>Админка</h2>
        {% block menu %}
        <div>
            {% include 'adminapp/includes/inc_menu.html' %}
        </div>
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

geekshop/adminapp/templates/adminapp/list.html
{% extends 'adminapp/base.html' %}

{% block content %}
<h2>{{ title|title }}</h2>
<a href="{% url create_link %}">{{ create_tag }}</a>
<ul>
    {% for object in object_list %}
    <li>
        <a href="{% url update_link object.pk %}" {% if object.is_active == False %} style="opacity: 0.5" {% endif %}>
            {% if request.resolver_match.url_name == 'users' %}
                {{ object.username|title }}
            {% else %}
                {{ object.name|title }}
            {% endif %}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

geekshop/adminapp/templates/adminapp/object_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<div class="user_delete">
    Уверены, что хотите удалить {{ object.username }}?
    <form method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'admin_custom:categories' %}">
            Отмена
        </a>
    </button>
</div>
</body>
</html>

geekshop/adminapp/templates/adminapp/object_update.html
{% extends 'adminapp/base.html' %}

{% block title %}
<title>{{title|title}}. Админка</title>
{% endblock %}

{% block content %}
<h2>{{title}}</h2>
{% if request.resolver_match.url_name != 'category_create' and request.resolver_match.url_name != 'user_create' %}
    <a href="{% url delete_link object.pk %}">{{tag}}</a>
{% endif %}
<form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Применить">
</form>
{% endblock %}

geekshop/adminapp/templates/adminapp/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h1>{{ object.name }}</h1>
<img width="200" src='/media/{{ object.image }}/'>
<p>{{ object.short_desc }}</p>
<a href="{% url 'admin_custom:product_update' object.pk %}">Редактировать</a>
<br>
<a href="{% url 'admin_custom:product_delete' object.pk %}">Удалить</a>
<br>
<br>
<a href="{% url 'admin_custom:products' %}"> <-- Ко всем продуктам</a>
</body>
</html>

geekshop/adminapp/templates/adminapp/product_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Применить">
</form>
</body>
</html>

geekshop/adminapp/templates/adminapp/products.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h2>Админка</h2>
<div>
    {% include 'adminapp/includes/inc_menu.html' %}
</div>
<h2>Категории</h2>
{% include 'adminapp/includes/inc_category_menu.html' %}
<h2>Продукты</h2>
<a href="{% url 'admin_custom:product_create' %}">Создать новый продукт</a>
<ul>
    {% for object in object_list %}
    <li>
        <a href="{% url 'admin_custom:product_read' object.pk %}">{{ object.name }}</a>
    </li>
    {% endfor %}
</ul>
</body>
</html>