geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

geekshop/basketapp/urls.py
from django.urls import path

from .views import add, remove, basket, edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='read'),
    path('add/<int:product_pk>/', add, name='add'),
    path('remove/<int:product_pk>', remove, name='remove'),
    path('edit/<int:pk>/', edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/',  include('mainapp.urls', namespace='products')),
    path('product_detail/<int:pk>/', mainapp.product_detail, name='product_detail'),
    path('contact/', mainapp.contacts, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='наименование категории', max_length=255, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_hot = models.BooleanField(verbose_name='горячий продукт', default=False)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def main(request):
    title = 'Interior product'

    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()

    content = {
        'title': title,
        'basket': basket,
    }
    return render(request, 'mainapp/index.html', context=content)


def products(request, pk=None, page=1):
    title = 'Interior product'
    categories = ProductCategory.objects.all()
    products = Product.objects.all()

    basket = []
    if request.user.is_authenticated:
       basket = request.user.basket.all()

    if pk or pk == 0:
        if pk !=0:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = products.filter(category=category)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'categories': categories,
            'products': products_paginator,
            'basket': basket,
        }
        return render(request, 'mainapp/products.html', context=content)
    else:
        hot_products = products.filter(is_hot=True)

        paginator = Paginator(hot_products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'hot_products': products_paginator,
            'categories': categories,
            'basket': basket,
        }
        return render(request, 'mainapp/hot_products.html', content)


def product_detail(request, pk=None):
    title = 'Interior product'
    categories = ProductCategory.objects.all()
    products = Product.objects.all()

    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket.all()

    if pk:
        product = get_object_or_404(ProductCategory, pk=pk)
        product = products.filter(pk=product.pk).first()

    content = {
        'title': title,
        'categories': categories,
        'product': product,
        'basket': basket,
    }
    return render(request, 'mainapp/product_detail.html', context=content)


def contacts(request):
    return render(request, 'mainapp/contact.html')

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8">

    {% block title %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700&display=swap" rel="stylesheet">

    {% block js %}
    {% endblock %}

</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
    <title>Interior product</title>
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="top-nav padding-site">
            <div class="navbar clearfix">
                {% include 'mainapp/includes/inc_menu.html' %}
                <h2 class="nav-content">Contact Us</h2> </div>
        </div>
        <div class="location clearfix">
            <div class="location-block"> <img src="{% static '/img/geo.png' %}" alt="" class="location-tag">
                <h3 class="location-name">California</h3>
                <p class="location-details">Phone:
                    <br><span class="l-bold">1900 - 1234 -5678</span>
                    <br>
                    <br>Email:
                    <br><span class="l-bold">info@interior.com</span>
                    <br>
                    <br>Address:
                    <br><span class="l-address">12 W 1st St, 90001 Los Angeles, California</span></p>
            </div>
            <div class="location-block"> <img src="{% static '/img/geo.png' %}" alt="" class="location-tag">
                <h3 class="location-name">California</h3>
                <p class="location-details">Phone:
                    <br><span class="l-bold">1900 - 1234 -5678</span>
                    <br>
                    <br>Email:
                    <br><span class="l-bold">info@interior.com</span>
                    <br>
                    <br>Address:
                    <br><span class="l-address">12 W 1st St, 90001 Los Angeles, California</span></p>
            </div>
            <div class="location-block location-block-last"> <img src="{% static '/img/geo.png' %}" alt="" class="location-tag">
                <h3 class="location-name">California</h3>
                <p class="location-details">Phone:
                    <br><span class="l-bold">1900 - 1234 -5678</span>
                    <br>
                    <br>Email:
                    <br><span class="l-bold">info@interior.com</span>
                    <br>
                    <br>Address:
                    <br><span class="l-address">12 W 1st St, 90001 Los Angeles, California</span></p>
            </div>
        </div>
        <div class="footer padding-site clearfix">
            <div class="contact-us">
                <p class="footer-tag">Contact Us</p>
                <p class="footer-text">132A Bridge Road Richmond VIC Australia.
                    <br>
                    <br>Talk to us on 1300 132
                    <br>info@interior.com</p>
            </div>
            <div class="information clearfix">
                <p class="footer-tag">Useful Information</p>
                <ul class="info-menu-left">
                    <li class="info-list"><a href="#" class="info-link">Sales terms</a></li>
                    <li class="info-list"><a href="#" class="info-link">Customer care</a></li>
                    <li class="info-list"><a href="#" class="info-link">Delivery</a></li>
                </ul>
                <ul class="info-menu-right">
                    <li class="info-list"><a href="#" class="info-link">Architect accounts</a></li>
                    <li class="info-list"><a href="#" class="info-link">Careers</a></li>
                    <li class="info-list"><a href="#" class="info-link">Exchanges&nbsp;&amp;&nbsp;returns</a></li>
                </ul>
            </div>
            <div class="suscribe">
                <p class="footer-tag">Let’s Stay in Touch!</p>
                <p class="footer-text">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                <input type="text" class="suscribe-input" placeholder="your email address"> </div>
        </div>
        <div class="copyright-block padding-site">
            <div class="copyright-text">&copy;&nbsp;Copyright - INTERIOR {% now "Y" %}. All Rights Reserved.</div>
            <div class="social">
                <a href=""><img src="{% static '/img/social-links.png' %}" alt=""></a>
            </div>
            <div class="copyright-text">Terms&nbsp;&amp;&nbsp;Conditions / Privacy policy&nbsp;&amp;&nbsp;Cookies</div>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/hot_products.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>{{title}}</title>
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="top-nav padding-site">
            <div class="navbar clearfix">
                {% include 'mainapp/includes/inc_menu.html' %}
                <h2 class="nav-content">Our Hot Products Range</h2>
                {% if basket %}
                <div>Количество продуктов в корзине: {{ request.user|basket_total_quantity }}</div>
                <div>
                    Общая стоимость корзины: {{ request.user|basket_total_cost }} руб.
                    <a href="{% url 'basket:read' %}">Перейти в корзину</a>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="products">
            <div class="title-menu clearfix">
                <ul>
                    <li class="title-list {% if request.resolver_match.kwargs.pk == 0 %}
                                                title-list-active
                                                {% endif %}">
                        <a href="{% url 'products:index' %}" class="title-link">All</a>
                    </li>
                    {% for category in categories %}
                        <li class="title-list {% if request.resolver_match.kwargs.pk == category.pk %}
                                                title-list-active
                                                {% endif %}">
                            <a href="{% url 'products:category' category.pk %}" class="title-link">{{ category.name|title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="products-block">
                {% for product in hot_products %}
                    <a href="{% url 'product_detail' product.pk %}" class="img-link"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                {% endfor %}
             </div>
             <div class="load"><a href="#" class="load-link"><img src="../../../static/img/load.png" alt=""></a></div>
         </div>
         <div class="promo-product clearfix">
             <div class="promo-content-1">
                 <p class="promo-tag">exclusive</p>
                 <h2 class="promo-name">Fishnet Chair</h2>
                 <p class="promo-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p><a class="btn" href="#">Order us <img src="../../../static/img/arrow.svg" alt="Right"></a></div>
             <div class="promo-content-2">
                 <p class="promo-tag">exclusive</p>
                 <h2 class="promo-name">Fishnet Chair</h2>
                 <p class="promo-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p><a class="btn" href="#">Order us <img src="../../../static/img/arrow.svg" alt="Right"></a></div>
         </div>
         <div class="footer padding-site clearfix">
             <div class="contact-us">
                 <p class="footer-tag">Contact Us</p>
                 <p class="footer-text">132A Bridge Road Richmond VIC Australia.
                     <br>
                     <br>Talk to us on 1300 132
                     <br>info@interior.com</p>
             </div>
             <div class="information clearfix">
                 <p class="footer-tag">Useful Information</p>
                 <ul class="info-menu-left">
                     <li class="info-list"><a href="#" class="info-link">Sales terms</a></li>
                     <li class="info-list"><a href="#" class="info-link">Customer care</a></li>
                     <li class="info-list"><a href="#" class="info-link">Delivery</a></li>
                 </ul>
                 <ul class="info-menu-right">
                     <li class="info-list"><a href="#" class="info-link">Architect accounts</a></li>
                     <li class="info-list"><a href="#" class="info-link">Careers</a></li>
                     <li class="info-list"><a href="#" class="info-link">Exchanges&nbsp;&amp;&nbsp;returns</a></li>
                 </ul>
             </div>
             <div class="suscribe">
                 <p class="footer-tag">Let’s Stay in Touch!</p>
                 <p class="footer-text">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                 <input type="text" class="suscribe-input" placeholder="your email address"> </div>
         </div>
         <div class="copyright-block padding-site">
             <div class="copyright-text">&copy;&nbsp;Copyright - INTERIOR {% now "Y" %}. All Rights Reserved.</div>
             <div class="social"><a href=""><img src="../../../static/img/social-links.png" alt=""></a> </div>
             <div class="copyright-text">Terms&nbsp;&amp;&nbsp;Conditions / Privacy policy&nbsp;&amp;&nbsp;Cookies</div>
         </div>
     </div>
 {% endblock %}

geekshop/mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
<title>{{title}}</title>
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="top-nav padding-site">
            <div class="navbar clearfix">
                {% include 'mainapp/includes/inc_menu.html' %}
                <h2 class="nav-content">{{product.name|title}}</h2>
                <div>Количество продуктов в корзине: {{ request.user|basket_total_quantity }}</div>
                <div>Общая стоимость корзины: {{ request.user|basket_total_cost }} руб.</div>
            </div>
        </div>
        <div class="products">
            <div class="title-menu clearfix">
                <ul>
                    <li class="title-list {% if request.resolver_match.kwargs.pk == 0 %}
                                                    title-list-active
                                                    {% endif %}">
                        <a href="{% url 'products:index' %}" class="title-link">All</a>
                    </li>
                    {% for category in categories %}
                    <li class="title-list {% if request.resolver_match.kwargs.pk == category.pk %}
                                                    title-list-active
                                                    {% endif %}">
                        <a href="{% url 'products:category' category.pk %}" class="title-link">{{ category.name|title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="products-block">
                <img src="{{product.image.url}}" alt="{{product.name}}">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name|title }}</h5>
                    <p class="card-text">{{ product.short_desc }}</p>
                    <p class="card-text">Цена: {{ product.price }} руб.</p>
                    <p class="card-text">Осталось: {{ product.quantity }} шт.</p>
                    <a href="{% url 'basket:add' product.pk %}">Добавить в корзину</a>
                    <br>
                    <a href="{% url 'basket:remove' product.pk %}">Удалить из корзины</a>
                </div>
            </div>
            <div class="load"><a href="#" class="load-link"><img src="../../../static/img/load.png" alt=""></a></div>
        </div>
        <div class="promo-product clearfix">
            <div class="promo-content-1">
                <p class="promo-tag">exclusive</p>
                <h2 class="promo-name">Fishnet Chair</h2>
                <p class="promo-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p><a class="btn" href="#">Order us <img src="../../../static/img/arrow.svg" alt="Right"></a></div>
            <div class="promo-content-2">
                <p class="promo-tag">exclusive</p>
                <h2 class="promo-name">Fishnet Chair</h2>
                <p class="promo-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p><a class="btn" href="#">Order us <img src="../../../static/img/arrow.svg" alt="Right"></a></div>
        </div>
        <div class="footer padding-site clearfix">
            <div class="contact-us">
                <p class="footer-tag">Contact Us</p>
                <p class="footer-text">132A Bridge Road Richmond VIC Australia.
                    <br>
                    <br>Talk to us on 1300 132
                    <br>info@interior.com</p>
            </div>
            <div class="information clearfix">
                <p class="footer-tag">Useful Information</p>
                <ul class="info-menu-left">
                    <li class="info-list"><a href="#" class="info-link">Sales terms</a></li>
                    <li class="info-list"><a href="#" class="info-link">Customer care</a></li>
                    <li class="info-list"><a href="#" class="info-link">Delivery</a></li>
                </ul>
                <ul class="info-menu-right">
                    <li class="info-list"><a href="#" class="info-link">Architect accounts</a></li>
                    <li class="info-list"><a href="#" class="info-link">Careers</a></li>
                    <li class="info-list"><a href="#" class="info-link">Exchanges&nbsp;&amp;&nbsp;returns</a></li>
                </ul>
            </div>
            <div class="suscribe">
                <p class="footer-tag">Let’s Stay in Touch!</p>
                <p class="footer-text">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                <input type="text" class="suscribe-input" placeholder="your email address"> </div>
        </div>
        <div class="copyright-block padding-site">
            <div class="copyright-text">&copy;&nbsp;Copyright - INTERIOR {% now "Y" %}. All Rights Reserved.</div>
            <div class="social"><a href=""><img src="../../../static/img/social-links.png" alt=""></a> </div>
            <div class="copyright-text">Terms&nbsp;&amp;&nbsp;Conditions / Privacy policy&nbsp;&amp;&nbsp;Cookies</div>
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load custom_tags %}

{% block title %}
    <title>{{title}}</title>
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="top-nav padding-site">
            <div class="navbar clearfix">
                {% include 'mainapp/includes/inc_menu.html' %}
                <h2 class="nav-content">Our Products Range</h2>
                {% if basket %}
                <div>Количество продуктов в корзине: {{ request.user|basket_total_quantity }}</div>
                <div>Общая стоимость корзины: {{ request.user|basket_total_cost }} руб.</div>
                {% endif %}
            </div>
        </div>
        <div class="products">
            <div class="title-menu clearfix">
                <ul>
                    <li class="title-list {% if request.resolver_match.kwargs.pk == 0 %}
                                                title-list-active
                                                {% endif %}">
                        <a href="{% url 'products:index' %}" class="title-link">All</a>
                    </li>
                    {% for category in categories %}
                        <li class="title-list {% if request.resolver_match.kwargs.pk == category.pk %}
                                                title-list-active
                                                {% endif %}">
                            <a href="{% url 'products:category' category.pk %}" class="title-link">{{ category.name|title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="products-block">
                {% for product in products %}
                    <a href="{% url 'product_detail' product.pk %}" class="img-link"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
                {% endfor %}
             </div>
             <div class="paginator">
                 {% if products.has_previous %}
                     <a href="{% url 'products:page'
                                 category.pk products.previous_page_number %}">
                         <
                     </a>
                 {% endif %}
                 <span class="current">страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
                 {% if products.has_next %}
                     <a href="{% url 'products:page'
                                 category.pk products.next_page_number %}">
                         >
                     </a>
                 {% endif %}
             </div>
         </div>
         <div class="promo-product clearfix">
             <div class="promo-content-1">
                 <p class="promo-tag">exclusive</p>
                 <h2 class="promo-name">Fishnet Chair</h2>
                 <p class="promo-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p><a class="btn" href="#">Order us <img src="../../../static/img/arrow.svg" alt="Right"></a></div>
             <div class="promo-content-2">
                 <p class="promo-tag">exclusive</p>
                 <h2 class="promo-name">Fishnet Chair</h2>
                 <p class="promo-content">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p><a class="btn" href="#">Order us <img src="../../../static/img/arrow.svg" alt="Right"></a></div>
         </div>
         <div class="footer padding-site clearfix">
             <div class="contact-us">
                 <p class="footer-tag">Contact Us</p>
                 <p class="footer-text">132A Bridge Road Richmond VIC Australia.
                     <br>
                     <br>Talk to us on 1300 132
                     <br>info@interior.com</p>
             </div>
             <div class="information clearfix">
                 <p class="footer-tag">Useful Information</p>
                 <ul class="info-menu-left">
                     <li class="info-list"><a href="#" class="info-link">Sales terms</a></li>
                     <li class="info-list"><a href="#" class="info-link">Customer care</a></li>
                     <li class="info-list"><a href="#" class="info-link">Delivery</a></li>
                 </ul>
                 <ul class="info-menu-right">
                     <li class="info-list"><a href="#" class="info-link">Architect accounts</a></li>
                     <li class="info-list"><a href="#" class="info-link">Careers</a></li>
                     <li class="info-list"><a href="#" class="info-link">Exchanges&nbsp;&amp;&nbsp;returns</a></li>
                 </ul>
             </div>
             <div class="suscribe">
                 <p class="footer-tag">Let’s Stay in Touch!</p>
                 <p class="footer-text">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                 <input type="text" class="suscribe-input" placeholder="your email address"> </div>
         </div>
         <div class="copyright-block padding-site">
             <div class="copyright-text">&copy;&nbsp;Copyright - INTERIOR {% now "Y" %}. All Rights Reserved.</div>
             <div class="social"><a href=""><img src="../../../static/img/social-links.png" alt=""></a> </div>
             <div class="copyright-text">Terms&nbsp;&amp;&nbsp;Conditions / Privacy policy&nbsp;&amp;&nbsp;Cookies</div>
         </div>
     </div>
 {% endblock %}